apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nats
resources:
- stream-concert.yaml
- stream-venue.yaml
- stream-artist.yaml
- stream-user.yaml
- stream-notification.yaml
- stream-sales-phase.yaml
- stream-ticket-journey.yaml
- stream-ticket-email.yaml
- stream-organizer.yaml
- stream-media.yaml
- stream-poison.yaml
- consumer-ingest-concert.yaml
- consumer-notify-concert.yaml
- consumer-resolve-artist-name.yaml
- consumer-resolve-artist-image.yaml
- consumer-verify-user-email.yaml
- consumer-track-user-created.yaml
- consumer-track-user-logged-in.yaml
- consumer-track-artist-followed.yaml
- consumer-track-artist-unfollowed.yaml
- consumer-track-notification-subscribed.yaml
- consumer-track-notification-unsubscribed.yaml
- consumer-track-notification-delivered.yaml
- consumer-track-ticket-journey.yaml
- consumer-track-ticket-email.yaml
- consumer-analytics-organizer-created.yaml
- consumer-analytics-organizer-artist-associated.yaml
- consumer-notify-sales-phase.yaml
- consumer-notify-sales-reminder.yaml
- consumer-media-uploaded.yaml
