apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: notification
spec:
  name: NOTIFICATION
  subjects: ["NOTIFICATION.*"]
  storage: file
  retention: limits
  maxAge: 168h
  duplicateWindow: 2m
  discard: old
  replicas: 1
  preventDelete: true
