apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: artist
spec:
  name: ARTIST
  subjects: ["ARTIST.*"]
  storage: file
  retention: limits
  maxAge: 168h
  duplicateWindow: 2m
  discard: old
  replicas: 1
  preventDelete: true
