apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zitadel-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secret-manager
    kind: ClusterSecretStore
  target:
    name: zitadel-secrets
    creationPolicy: Owner
  data:
  - secretKey: ZITADEL_MASTERKEY
    remoteRef:
      key: zitadel-masterkey
