apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zitadel

resources:
- namespace.yaml
- serviceaccount.yaml
- deployment-api.yaml
- deployment-web.yaml
- service-api.yaml
- service-web.yaml
- httproute.yaml
- healthcheckpolicy.yaml
- pdb.yaml
- external-secret.yaml
- external-secret-postgres-admin.yaml
- external-secret-web-pat.yaml
- job-grant-db.yaml

configMapGenerator:
- name: zitadel-config
  envs:
  - configmap.env

labels:
- includeSelectors: false
  pairs:
    owner: zitadel
