apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zitadel
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: zitadel
      component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zitadel-login
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: zitadel
      component: login
