resources:
  operator:
    requests:
      cpu: 10m
      memory: 64Mi
      ephemeral-storage: 100Mi
    limits:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 100Mi
  metricServer:
    requests:
      cpu: 10m
      memory: 64Mi
      ephemeral-storage: 100Mi
    limits:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 100Mi
  webhooks:
    requests:
      cpu: 10m
      memory: 64Mi
      ephemeral-storage: 100Mi
    limits:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 100Mi
