apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: google-secret-manager-argocd
spec:
  # Restrict access to the argocd namespace only.
  # Separate from the backend ClusterSecretStore to isolate secret permissions.
  conditions:
  - namespaces:
    - argocd
  provider:
    gcpsm:
      # Replaced by overlay patch per environment
      projectID: TO_REPLACE_BY_OVERLAY
