apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/liverty-music/cloud-provisioning.git
    targetRevision: main
    path: k8s/namespaces/otel-collector/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: otel-collector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
