apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cronjob.yaml

labels:
- includeSelectors: true
  pairs:
    app: artist-image-sync

images:
- name: artist-image-sync
  newName: asia-northeast2-docker.pkg.dev/liverty-music-dev/backend/artist-image-sync
  newTag: latest

configMapGenerator:
- name: artist-image-sync-job-config
  envs:
  - configmap.env
