apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- server
- cronjob/concert-discovery
- cronjob/artist-image-sync
- cronjob/merch-discovery
- cronjob/sales-phase-discovery
- cronjob/sales-reminders
- consumer

namespace: backend
