apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cronjob.yaml

labels:
- includeSelectors: true
  pairs:
    app: official-site-refresh

images:
- name: official-site-refresh
  newName: asia-northeast2-docker.pkg.dev/liverty-music-dev/backend/official-site-refresh
  newTag: latest

configMapGenerator:
- name: official-site-refresh-job-config
  envs:
  - configmap.env
