apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-app
spec:
  scaleTargetRef:
    name: consumer-app
  minReplicaCount: 0
  maxReplicaCount: 3
  cooldownPeriod: 300
  pollingInterval: 30
  triggers:
  - type: nats-jetstream
    metadata:
      natsServerMonitoringEndpoint: "nats.nats.svc.cluster.local:8222"
      account: "$G"
      stream: "CONCERT"
      consumer: "CONCERT_discovered"
      lagThreshold: "10"
      activationLagThreshold: "1"
  - type: nats-jetstream
    metadata:
      natsServerMonitoringEndpoint: "nats.nats.svc.cluster.local:8222"
      account: "$G"
      stream: "CONCERT"
      consumer: "CONCERT_created"
      lagThreshold: "10"
      activationLagThreshold: "1"
  - type: nats-jetstream
    metadata:
      natsServerMonitoringEndpoint: "nats.nats.svc.cluster.local:8222"
      account: "$G"
      stream: "ARTIST"
      consumer: "ARTIST_created"
      lagThreshold: "1"
      activationLagThreshold: "1"
  - type: nats-jetstream
    metadata:
      natsServerMonitoringEndpoint: "nats.nats.svc.cluster.local:8222"
      account: "$G"
      stream: "USER"
      consumer: "USER_created"
      lagThreshold: "1"
      activationLagThreshold: "1"
