apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: server-policy
spec:
  default:
    timeoutSec: 150
    connectionDraining:
      drainingTimeoutSec: 60
  targetRef:
    group: ""
    kind: Service
    name: server-svc # Referenced via kustomizeconfig.yaml 'nameReference'
