apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: atlas-operator
    spec:
      template:
        spec:
          nodeSelector:
            cloud.google.com/gke-spot: "true"

# Right-size CPU request for dev
- target:
    kind: Deployment
    name: atlas-operator
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: atlas-operator
    spec:
      template:
        spec:
          containers:
          - name: manager
            resources:
              requests:
                cpu: 10m
