config:
  cluster:
    enabled: false
    replicas: 1

  jetstream:
    enabled: true
    fileStore:
      dir: /data
      pvc:
        enabled: true
        size: 10Gi
        storageClassName: premium-rwo

container:
  merge:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
        ephemeral-storage: 1Gi
      limits:
        cpu: 200m
        memory: 256Mi
        ephemeral-storage: 1Gi
    # GKE Autopilot injects these security defaults
    securityContext:
      capabilities:
        drop:
        - NET_RAW

reloader:
  merge:
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
        ephemeral-storage: 1Gi
      limits:
        cpu: 50m
        memory: 64Mi
        ephemeral-storage: 1Gi
    # GKE Autopilot injects these security defaults
    securityContext:
      capabilities:
        drop:
        - NET_RAW

natsBox:
  enabled: false

service:
  ports:
    monitor:
      enabled: true
