apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: google-secret-manager-argocd
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
  data:
  - secretKey: google-chat-webhook-url
    remoteRef:
      key: argocd-google-chat-webhook-url
